### PR TITLE
pfSense implementation under Xen hypervisor - introduction

### PR DESCRIPTION
**Pull request by piotr-kleins**

### CODE REVIEW

**Comment by artur-rs** [comment]
@piotr-kleins moved commits regarding your profile changes [here](https://github.com/3mdeb/news-and-ideas/pull/158)

**Comment by artur-rs** [comment]
@piotr-kleins please, sign all your commits, add an actual date in the metadata and file name, and set published metadata to `true`, then I can publish the post

**Comment by piotr-kleins** [comment]
@artur-rs Done, you can publish it.

**Comment by artur-rs** [comment]
@piotr-kleins commits are not signed yet

**Comment by piotr-kleins** [comment]
@artur-rs Now everything should be fine

**Pull request merged**
