### PR TITLE
Mobile menu

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by artur-rs** [comment]
@pietrushnic my only complaint can be rolled up menu (after clicking), but it's a matter of choice. In the 3mdeb WP layout, whole elements of menu are visible, when on hugo mobile, language and account options are hidden (user needs to scroll down).

I'll approve those changes and we can go back to fixing above request later.

ps. burger menu animation works only once after refresh - don't know if it's a feature or a bug :)

**Review by artur-rs — APPROVED** [review]

**Comment by pietrushnic** [comment]
> @pietrushnic my only complaint can be rolled up menu (after clicking), but it's a matter of choice. 

I would like to understand that one, since I don't completely get vision how it should work.

> In the 3mdeb WP layout, whole elements of menu are visible, when on hugo mobile, language and account options are hidden (user needs to scroll down).

Agree, but it depends on screen size. Definitely 3mdeb.com is smaller so it fits the screen. I think font can be little bit smaller to be more similar to 3mdeb.com.

> 
> I'll approve those changes and we can go back to fixing above request later.
> 
> ps. burger menu animation works only once after refresh - don't know if it's a feature or a bug :)

Yeah I noticed, I'm not sure what is the reason and reproducibility of that bug is quite weird. We will try to fix that.

**Comment by pietrushnic** [comment]
I'm wrong second problem is not case of font size, there is limit to the area where mobile menu pop up. We will try to fix that.

**Comment by pietrushnic** [comment]
@artur-rs please check, this is best what we can achieve. If there are no major issues, please merge both PRs and let's move that to production.

**Pull request merged**
